/** 45 categories for the Categories drinking game. */
export const CATEGORIES: string[] = [
  "Beer brands",
  "Pizza toppings",
  "Movie villains",
  "Things at a party",
  "Car brands",
  "Reasons to call in sick",
  "Ice cream flavors",
  "Superhero names",
  "Things in a hospital",
  "Countries in Europe",
  "Fast food chains",
  "Types of alcohol",
  "Board games",
  "Dog breeds",
  "Oscar-winning movies",
  "Things you find in a kitchen",
  "Sports teams",
  "Famous duos",
  "Things that are red",
  "Video game consoles",
  "Types of cheese",
  "Taylor Swift songs",
  "Cartoon characters",
  "Things on a dinner table",
  "U.S. states",
  "Cocktail names",
  "Famous Michaels",
  "Things you do before bed",
  "Reality TV shows",
  "Things in a backpack",
  "Shoe brands",
  "Disney movies",
  "Things that are sticky",
  "Types of pasta",
  "Celebrities named Chris",
  "Things in Las Vegas",
  "Holiday traditions",
  "Words that rhyme with 'drunk'",
  "Things in a gym",
  "Breakfast foods",
  "Bond movie titles",
  "Things you lose at a party",
  "Animals in the jungle",
  "Streaming services",
  "Excuses for being late",
];
