/** ~50 non-repeating "Most likely to…" prompts, mild → wild. */
export const PROMPTS: readonly string[] = [
  // Mild
  "become a millionaire",
  "survive a zombie apocalypse",
  "win a reality TV show",
  "write a bestselling novel",
  "move abroad and never come back",
  "still be awake at 4am for no reason",
  "forget someone's name the second they say it",
  "cry during a movie",
  "talk to strangers at a party",
  "get lost with GPS",
  "adopt five rescue animals",
  "quit their job on a whim",
  "become internet famous",
  "marry first",
  "start a cult — accidentally",
  "narrate their own life out loud",
  "fall asleep first tonight",
  "be the last one standing tomorrow morning",
  "bring up their ex unprompted",
  "order the weirdest thing on the menu",
  // Moderate
  "get kicked out of the bar tonight",
  "text their ex by 2am",
  "skinny dip before the night is over",
  "start a rumour and forget they started it",
  "flirt their way out of a speeding ticket",
  "wake up with a stranger's number and no memory of getting it",
  "go home with someone they just met",
  "steal a traffic cone as a trophy",
  "convince everyone to do one more round",
  "make out with someone in this room",
  "drunkenly redecorate someone's apartment",
  "try to cook at 3am and almost burn the place down",
  "end up on stage at a bar",
  "start an argument about something totally irrelevant",
  "make a terrible financial decision tonight",
  // Spicy
  "slide into someone's DMs at 2am",
  "get a spontaneous tattoo they'll regret",
  "hook up with someone they said they never would",
  "kiss more than one person tonight",
  "send a risky text to the wrong contact",
  "get into an argument with a bouncer",
  "dare someone into doing something illegal",
  "wake up not knowing how they got home",
  "do a body shot off a stranger",
  "start a drama that becomes the group chat topic for a week",
  "confess a secret they swore they'd take to the grave",
  "end the night crying happy tears on the dancefloor",
  "accidentally go viral for the worst possible reason",
  "ghost someone in this room one day",
  "get banned from a venue — and somehow still get back in",
] as const;
