/** 50 Drunk Jenga block dares / rules */
export const BLOCK_DARES: string[] = [
  "Everyone drinks!",
  "Waterfall — you start, everyone follows; no one stops until the person before them does.",
  "Make a new rule for the rest of the game. Break it = drink.",
  "Skip your next turn.",
  "Take 3 sips.",
  "Give out 4 sips to whoever you choose.",
  "Truth or Dare — pick one or take 2 sips.",
  "Two truths and a lie — group guesses; if they're wrong, they each drink.",
  "Never Have I Ever — one round; anyone who has done it drinks.",
  "Last person to put their hands on their head drinks.",
  "Accent round — everyone speaks in an accent until the next block is pulled.",
  "Pick a drinking buddy — they drink whenever you do until the tower falls.",
  "The player to your left takes 2 sips.",
  "The player to your right takes 2 sips.",
  "Social — everyone drinks!",
  "Rhyme time — say a word; go around rhyming; first to fail drinks.",
  "Category challenge — name a category; first to blank drinks.",
  "Thumb master — put your thumb on the table anytime; last to notice drinks.",
  "Confess your most embarrassing moment or take 3 sips.",
  "No pointing for the rest of the game — violators drink.",
  "The quietest player must do a 5-second dare from the group.",
  "Swap drinks with the person across from you.",
  "Mime a movie; others guess; if no one gets it in 30 s, you drink.",
  "No first names for the rest of the game — use nicknames or drink.",
  "Waterfall from the youngest player.",
  "The tallest player takes 2 sips.",
  "Sing the next sentence you say — or drink.",
  "Do your best celebrity impression or take 2 sips.",
  "Reveal a secret or take 3 sips.",
  "Everyone except you takes a sip.",
  "Take a sip for every year you've been alive — just kidding, max 3 sips.",
  "Rock Paper Scissors with the player of your choice — loser drinks.",
  "Name 5 countries in 10 seconds or drink.",
  "Tell a joke; if no one laughs, you drink.",
  "The person who laughs first after this card takes 2 sips.",
  "Compliment every player — or drink.",
  "You are now 'The Question Master' — anyone who answers your direct questions drinks, until the next pull.",
  "Arm wrestle the player of your choice — loser drinks.",
  "Do 10 seconds of your best dance or take 2 sips.",
  "Speak only in questions until the next block is pulled — slip up and drink.",
  "The last person who drank takes another sip.",
  "Pour a mystery pour into the center cup — someone will drink it when the tower falls.",
  "Everyone points to the person most likely to fall asleep — that person drinks.",
  "No swearing for 2 rounds — violators drink.",
  "Take 2 sips and pick someone to take 2 as well.",
  "Give your drink to any player.",
  "You must speak in third person until the next pull — slip up and drink.",
  "First person to check their phone after this must drink.",
  "Speed round — everyone names a cocktail; first repeat drinks.",
  "The floor is lava — last person to lift their feet drinks.",
];
