/** Dare/challenge lines shown after the bottle lands on a player. */
export const DARES: string[] = [
  "Take 2 sips and give the spinner a truth question.",
  "Do your best impression of someone in the circle.",
  "Take a drink and say something nice about the person across from you.",
  "Let the group pick a dare — or take 3 sips.",
  "Show your most embarrassing photo on your phone or drink.",
  "Call or text someone and tell them you miss them, or drink.",
  "Speak in an accent for the next two rounds or drink.",
  "Let the spinner read your last 5 texts or take 2 sips.",
  "Do 10 jumping jacks right now or drink.",
  "Say a tongue-twister three times fast or take 2 sips.",
  "Let the group scroll your camera roll for 15 seconds or drink.",
  "Give someone a compliment you've never told them before.",
  "Close your eyes and the spinner rearranges your phone apps.",
  "Swap drinks with the person next to you.",
  "Tell the group your most embarrassing drunk story or take 3 sips.",
  "Let the spinner change your social media profile pic for 10 minutes.",
  "Stand up and do your best dance move.",
  "Take a sip for every year older you are than 21.",
  "Act out a scene from your favourite movie or take 2 sips.",
  "Confess the last lie you told — or take 3 sips.",
  "Text your mum/dad a heart emoji with no context, or drink.",
  "Let the group give you a nickname for the rest of the night.",
  "Close your eyes and try to identify three people's voices.",
  "Speak only in questions for the next two minutes or drink.",
  "Post a selfie right now with a caption chosen by the spinner.",
  "Finish whatever is in your cup.",
  "Take a drink and share an unpopular opinion.",
  "Do a cartwheel or drink.",
  "Sing the chorus of the last song you listened to.",
  "Sip every time someone says your name for the next round.",
];
