/** 40 "Who in the group…" questions for Paranoia. */
export const QUESTIONS: string[] = [
  "Who in the group is most likely to accidentally send a risky text to the wrong person?",
  "Who in the group would survive longest in a zombie apocalypse?",
  "Who in the group is most likely to cry at a rom-com?",
  "Who in the group would be the worst roommate?",
  "Who in the group is most likely to ghost someone after a first date?",
  "Who in the group has the most embarrassing search history?",
  "Who in the group is most likely to start a bar fight — and lose?",
  "Who in the group would blow all their savings in Vegas?",
  "Who in the group is most likely to get a face tattoo on a dare?",
  "Who in the group has told the biggest lie tonight?",
  "Who in the group is most likely to hook up with someone at this party?",
  "Who in the group would sell everyone out first if things got bad?",
  "Who in the group is most likely to get kicked out of a club?",
  "Who in the group has the worst taste in exes?",
  "Who in the group would be the first to pass out tonight?",
  "Who in the group is most likely to have a secret OnlyFans?",
  "Who in the group would last the longest without their phone?",
  "Who in the group is most likely to make a drunken online purchase they regret?",
  "Who in the group gives the worst advice but acts like a life coach?",
  "Who in the group would go home with someone they just met?",
  "Who in the group is most likely to be famous one day — for the wrong reasons?",
  "Who in the group could lie to a lie detector and win?",
  "Who in the group is most likely to overstay their welcome at a party?",
  "Who in the group has the most unread messages in their phone right now?",
  "Who in the group would join a cult if the vibe was right?",
  "Who in the group is most likely to start unnecessary drama tonight?",
  "Who in the group smells the best after two hours of dancing?",
  "Who in the group would be voted off the island first?",
  "Who in the group has the most skeletons in their closet?",
  "Who in the group is most likely to cancel plans at the last minute?",
  "Who in the group would get roasted the hardest at their own birthday?",
  "Who in the group is most likely to be in a throuple?",
  "Who in the group would be the most useless on a camping trip?",
  "Who in the group is most likely to accidentally dial their ex at 2am?",
  "Who in the group is most likely to end up on a reality TV show?",
  "Who in the group has the most chaotic energy right now?",
  "Who in the group would be the first to rat on everyone in an interrogation?",
  "Who in the group is most likely to wake up married after a wild night out?",
  "Who in the group is most likely to be someone's guilty pleasure?",
  "Who in the group would give the most unhinged toast at a wedding?",
];
